In [1]:
import numpy as np
import numpy.matlib
import numpy.linalg

### x + y + z = 6
### 2y + 5z = -4
### 2x + 5y - z = 27
### 求解x,y,z

In [11]:
import numpy as np 
a = np.array([
    [1,1,1],
    [0,2,5],
    [2,5,-1]
]) 
print('数组 a：')
print(a) 
ainv = np.linalg.inv(a) 
print('a 的逆：')
print(ainv)
print('矩阵 b：')
b = np.array([[6],[-4],[27]]) 
print(b) 
print('计算：A^(-1)B：')
x = np.linalg.solve(a,b) 
print(x)
# 这就是线性方向 x = 5, y = 3, z = -2 的解

数组 a：
[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]
a 的逆：
[[ 1.28571429 -0.28571429 -0.14285714]
 [-0.47619048  0.14285714  0.23809524]
 [ 0.19047619  0.14285714 -0.0952381 ]]
矩阵 b：
[[ 6]
 [-4]
 [27]]
计算：A^(-1)B：
[[ 5.]
 [ 3.]
 [-2.]]


In [12]:
x = np.dot(ainv,b)
x

array([[ 5.],
       [ 3.],
       [-2.]])